### ISSUE TITLE
[Feat] Decrease the size of badge

### ISSUE THREAD

**Issue by Bhavishya2601** [rajatuiwebdev/badge-website#107]
### Description

the badge size is too big, it doesn't look good and professional

i would like to change it and smaller it's size under hactoberfest

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rajatuiwebdev/badge-website/blob/main/CONTRIBUTING.md)
- [ ] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by askarthikey** [comment]
Heyy I would like to contribute to this. Can you please assign me
