### ISSUE TITLE
Add share on social media button

### ISSUE THREAD

**Issue by rajatuiwebdev** [rajatuiwebdev/badge-website#11]
What is the use of a badge, if you can't even flaunt it? Add a button to share the badge on social media using open APIs.

**Comment by Abhineetsahay** [comment]
Hello @rajatuiwebdev  can you assign me this task to me?

**Comment by SHIVAM123P** [comment]
Hey @rajatuiwebdev I have gone through your project, I would like to contribute to it, Can you assign this issue to me?
