### ISSUE TITLE
Favicon to the website

### ISSUE THREAD

**Issue by SahilShaw2004** [rajatuiwebdev/badge-website#19]
Adding a favicon to the site such that it gives it a professional look.Assign me this task under Hactoberfest'24

**Comment by prayag78** [comment]
Hello @SahilShaw2004 
I would like to complete this task.

**Comment by Kedarnath-Rothe** [comment]
Please Assign this issue to me under hactoberfest label

**Comment by SahilShaw2004** [comment]
@rajatuiwebdev but i already did the tak how can you reassign it?

**Comment by Kedarnath-Rothe** [comment]
I have added Favicon please review my PR... and merge if id ok.....
![Screenshot 2024-10-03 164526](https://github.com/user-attachments/assets/ac370229-07cd-431c-be85-b5e8a0d5ce8c)

**Comment by Kedarnath-Rothe** [comment]
can you please label this issue as hacktoberfest-accepted...
