### ISSUE TITLE
Add About Page to the Website

### ISSUE THREAD

**Issue by ramith-kulal** [rajatuiwebdev/badge-website#42]
### What:
I propose adding an "About" page to the website that gives users a brief overview of the site's purpose, such as showcasing badges 

### Why:
Currently, the website does not have an "About" page, which is a common section for most websites. This would help improve the user experience by explaining what the site is about.

### How:
1. Create a new HTML page (`about.html`) with the necessary structure and content.
2. Add some information about the website's purpose, Hacktoberfest involvement, and how users can contribute.
3. Link the "About" page from the navigation bar or the footer.

would like to work on this under hactoberfest'24

**Comment by IvySaskia** [comment]
Hey! I came for Hacktoberfest, I would like to contribute to this issue.

**Comment by DPxxxxxx** [comment]
hey i am interested can i contribute to the issue
