### ISSUE TITLE
Add proper meta tags for good SEO

### ISSUE THREAD

**Issue by rajatuiwebdev** [rajatuiwebdev/badge-website#6]
There's this issue that this website does not have proper meta tags which can result in poor SEO; if you can solve it, I'll assign this issue to you under Hacktoberfest.

**Comment by kanchanraiii** [comment]
kindly assign this issue :)

**Comment by rajatuiwebdev** [comment]
Assigned. Good luck.

**Comment by kanchanraiii** [comment]
please check PR #8
